version: "2.2"
services:
  nginx:
    image: nginx:1.16
    depends_on:
     - php-fpm
    links:
     - php-fpm
    environment:
     - NGINX_PORT=80
     - FASTCGI_HOST=php-fpm
     - FASTCGI_PORT=9000
     - DOCUMENT_ROOT=/usr/local/src/lessons.local/public
     - UPLOAD_MAX_FILESIZE=32M
    ports:
     - 8701:80
    volumes:
     - ${BITBUCKET_CLONE_DIR}/stack/nginx/templates/default.conf.template:/etc/nginx/conf.d/default.conf.template
     - ${BITBUCKET_CLONE_DIR}/stack/nginx/entrypoint.sh:/entrypoint.sh
    volumes_from:
     - php-fpm
    command: "/bin/bash /entrypoint.sh"

  php-fpm:
    image: itdevgroup/php-fpm7.4
    volumes:
     - ${BITBUCKET_CLONE_DIR}:/usr/local/src/lessons.local
    working_dir: /usr/local/src/lessons.local
    extra_hosts:
     - "localhost:127.0.0.1"
    env_file:
      - ${BITBUCKET_CLONE_DIR}/stack/environment/testing/php-fpm.env
volumes:
  data: 
    driver:
      local
