version: "2"
services:
  nginx:
    image: nginx:1.14
    depends_on:
     - php-fpm
    links:
     - php-fpm
    environment:
     - NGINX_PORT=80
     - FASTCGI_HOST=php-fpm
     - FASTCGI_PORT=9000
     - DOCUMENT_ROOT=${APP_PROJECT_PATH}/public
     - UPLOAD_MAX_FILESIZE=500M
     - CORS_SERVER_NAME=localhost|bmt.loc
    ports:
     - ${NGINX_HOST_HTTP_PORT}:80
     - ${NGINX_HOST_HTTPS_PORT}:443
    volumes:
     - ./stack/nginx/templates/default.conf.template:/etc/nginx/conf.d/default.conf.template
     - ./stack/nginx/entrypoint.sh:/entrypoint.sh
    volumes_from:
     - php-fpm
    command: "/bin/bash /entrypoint.sh"

  database:
    image: mysql:${MYSQL_VERSION}
    ports:
     - ${MYSQL_EXTERNAL_PORT}:3306
    volumes:
     - data:/var/lib/mysql
     - ./stack/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
     - MYSQL_DATABASE=${MYSQL_DATABASE}
     - MYSQL_USER=${MYSQL_USER}
     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  php-fpm:
    image: itdevgroup/php-fpm7.2
    depends_on:
     - database
     - redis
    links:
     - database
     - redis
    volumes:
     - .:${APP_PROJECT_PATH}
    working_dir: ${APP_PROJECT_PATH}
    extra_hosts:
     - "localhost:127.0.0.1"

  redis:
    image: redis
    ports:
     - ${REDIS_PORT}:6379
    volumes:
     - data:/var/lib/redis

  node:
    image: "node:10.18.1"
    restart: "no"
    working_dir: ${APP_PROJECT_PATH}
    environment:
      - NODE_ENV=dev
    volumes:
     - .:${APP_PROJECT_PATH}
    command: "npm run dev"

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
    - "1025:1025"
    - "8025:8025"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
    - database
    ports:
    - 9191:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: database
      PMA_PORT: 3306

  queue-worker:
    image: itdevgroup/php-fpm7.2
    restart: always
    entrypoint: /usr/bin/supervisord -n
    depends_on:
      - database
      - redis
    links:
      - database
      - redis
    volumes:
      - .:${APP_PROJECT_PATH}
      - ./stack/supervisord/development/:/etc/supervisor/conf.d/
    working_dir: ${APP_PROJECT_PATH}
    extra_hosts:
      - "localhost:127.0.0.1"
    ports:
      - "9001:9001"

volumes:
  data: {}
