version: "2.2"
services:
  nginx:
    image: nginx:1.14
    depends_on:
      - php-fpm
    links:
      - php-fpm
    environment:
      - NGINX_PORT=80
      - FASTCGI_HOST=php-fpm
      - FASTCGI_PORT=9000
      - DOCUMENT_ROOT=/usr/local/src/lessons.local/public
      - UPLOAD_MAX_FILESIZE=32M
    ports:
      - 8701:80
    volumes:
      - ./stack/nginx/templates/default.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./stack/nginx/entrypoint.sh:/entrypoint.sh
    volumes_from:
      - php-fpm
    command: "/bin/bash /entrypoint.sh"

  php-fpm:
    build:
      context: ./stack/docker
      args:
        INSTALL_XDEBUG: 'true'
    volumes:
      - .:/usr/local/src/lessons.local
      - ./stack/docker/xdebug.ini:/etc/php/7.2/mods-available/xdebug.ini
    working_dir: /usr/local/src/lessons.local
    extra_hosts:
      - "accounts:127.0.0.1"
    env_file:
      - ./stack/environment/testing/node.env
      - ./stack/environment/testing/mail.env
      - ./stack/environment/testing/php-fpm.env
    environment:
      - PHP_IDE_CONFIG="serverName=Docker"

volumes:
  data:
    driver:
      local
